// frontend/src/views/features/index.vue
<script setup lang="ts">
import { computed, reactive, ref } from "vue";
import { useBoolean } from "@sa/hooks";
import { useAntdvForm } from "@/hooks/common/form";
import { useAntdvPaginatedTable, useTableOperate } from "@/hooks/common/table";
import { createFeature, deleteFeature, fetchFeatures, updateFeature } from "@/service/api";
import { formatDateTime, getServiceErrorMessage, unwrapFlatData } from "@/utils/lykn";

const searchModel = reactive({
  keyword: "",
  enabled: undefined as "true" | "false" | undefined,
});

const { formRef, validate, restoreValidation } = useAntdvForm();
const paginationParams = reactive({
  current: 1,
  size: 10,
});
const tableScrollX = 1284;

const modalOpen = ref(false);
const submitting = ref(false);
const operateType = ref<AntdvUI.TableOperateType>("add");
const editingId = ref<number>();

const formModel = reactive<Api.Lykn.FeaturePayload>({
  code: "",
  name: "",
  description: "",
  enabled: true,
});

const enabledOptions = [
  { label: "启用", value: "true" },
  { label: "停用", value: "false" },
];

const searchItems = computed(() => [
  { key: "keyword", label: "关键词", placeholder: "功能编码 / 名称 / 描述" },
  {
    key: "enabled",
    label: "状态",
    type: "select" as const,
    placeholder: "请选择状态",
    options: enabledOptions,
  },
]);

const formRules = {
  code: [{ required: true, message: "请输入功能编码" }],
  name: [{ required: true, message: "请输入功能名称" }],
};

const { loading, data, columns, columnChecks, getData, getDataByPage, mobilePagination } =
  useAntdvPaginatedTable({
    api: fetchFeatures,
    transform: (response) => {
      const records = unwrapFlatData(response, "加载功能列表失败") as Api.Lykn.FeatureRecord[];
      const keyword = searchModel.keyword.trim().toLowerCase();

      const filteredRecords = records.filter((item) => {
        const matchKeyword =
          !keyword ||
          item.code.toLowerCase().includes(keyword) ||
          item.name.toLowerCase().includes(keyword) ||
          item.description.toLowerCase().includes(keyword);
        const matchEnabled =
          searchModel.enabled === undefined || String(item.enabled) === searchModel.enabled;

        return matchKeyword && matchEnabled;
      });

      return {
        data: filteredRecords,
        pageNum: paginationParams.current,
        pageSize: paginationParams.size,
        total: filteredRecords.length,
      };
    },
    onPaginationParamsChange: (params) => {
      paginationParams.current = params.current || 1;
      paginationParams.size = params.pageSize || 10;
    },
    columns: () => [
      { key: "index", title: "序号", align: "center", width: 64, fixed: "left" },
      { key: "name", dataIndex: "name", title: "功能", align: "left", width: 180, fixed: "left" },
      { key: "code", dataIndex: "code", title: "编码", align: "left", width: 160 },
      { key: "enabled", dataIndex: "enabled", title: "状态", align: "center", width: 100 },
      { key: "description", dataIndex: "description", title: "描述", align: "left", width: 280 },
      {
        key: "updated_at",
        dataIndex: "updated_at",
        title: "更新时间",
        align: "center",
        width: 180,
      },
      {
        key: "created_at",
        dataIndex: "created_at",
        title: "创建时间",
        align: "center",
        width: 180,
      },
      { key: "operate", title: "操作", align: "center", width: 140, fixed: "right" },
    ],
  });

const { checkedRowKeys, onBatchDeleted } = useTableOperate(data, "id", getData);
const { bool: batchDeleting, setBool: setBatchDeleting } = useBoolean();
const rowSelection = computed(() => ({
  fixed: true,
  selectedRowKeys: checkedRowKeys.value,
  onChange: (keys: (string | number)[]) => {
    checkedRowKeys.value = keys as string[];
  },
}));

const modalTitle = computed(() => (operateType.value === "add" ? "新建功能" : "编辑功能"));

function handleSearch() {
  getDataByPage();
}

function resetSearch() {
  searchModel.keyword = "";
  searchModel.enabled = undefined;
  getDataByPage();
}

function resetForm() {
  editingId.value = undefined;
  formModel.code = "";
  formModel.name = "";
  formModel.description = "";
  formModel.enabled = true;
  void restoreValidation();
}

function openCreateModal() {
  resetForm();
  operateType.value = "add";
  modalOpen.value = true;
}

function openEditModal(record: Api.Lykn.FeatureRecord) {
  operateType.value = "edit";
  editingId.value = record.id;
  formModel.code = record.code;
  formModel.name = record.name;
  formModel.description = toFeature(record).description;
  formModel.enabled = toFeature(record).enabled;
  modalOpen.value = true;
}

async function submitForm() {
  await validate();

  submitting.value = true;
  try {
    if (operateType.value === "add") {
      unwrapFlatData(await createFeature({ ...formModel }), "创建功能失败");
      window.$message?.success("功能已创建");
    } else if (editingId.value) {
      unwrapFlatData(await updateFeature(editingId.value, { ...formModel }), "更新功能失败");
      window.$message?.success("功能已更新");
    }

    modalOpen.value = false;
    await getDataByPage();
  } catch (error) {
    window.$message?.error(getServiceErrorMessage(error));
  } finally {
    submitting.value = false;
  }
}

function toFeature(record: unknown) {
  return record as Api.Lykn.FeatureRecord;
}

async function handleBatchDelete() {
  setBatchDeleting(true);
  try {
    await Promise.all(checkedRowKeys.value.map((id) => deleteFeature(Number(id))));
    await onBatchDeleted();
  } catch (error) {
    checkedRowKeys.value = [];
    window.$message?.error(getServiceErrorMessage(error, "批量删除功能失败"));
    await getDataByPage();
  } finally {
    setBatchDeleting(false);
  }
}

async function removeFeature(record: Api.Lykn.FeatureRecord) {
  try {
    unwrapFlatData(await deleteFeature(record.id), "删除功能失败");
    window.$message?.success("功能已删除");
    await getDataByPage();
  } catch (error) {
    window.$message?.error(getServiceErrorMessage(error));
  }
}
</script>

<template>
  <div class="min-h-500px flex-col-stretch gap-16px overflow-hidden lt-sm:overflow-auto">
    <QuerySearchForm
      v-model:model="searchModel"
      :items="searchItems"
      :loading="loading"
      @search="handleSearch"
      @reset="resetSearch"
    />

    <ACard
      title="功能管理"
      variant="borderless"
      :body-style="{ flex: 1, overflow: 'hidden' }"
      class="flex-col-stretch sm:flex-1-hidden card-wrapper"
    >
      <template #extra>
        <TableHeaderOperation
          v-model:columns="columnChecks"
          :disabled-delete="checkedRowKeys.length === 0"
          :loading="loading"
          @refresh="getData"
        >
          <template #default>
            <AButton size="small" ghost type="primary" @click="openCreateModal">
              <template #icon>
                <icon-ic-round-plus class="text-icon" />
              </template>
              新建功能
            </AButton>
            <APopconfirm title="确认删除吗？" @confirm="handleBatchDelete">
              <AButton
                size="small"
                ghost
                danger
                :disabled="checkedRowKeys.length === 0"
                :loading="batchDeleting"
              >
                <template #icon>
                  <icon-ic-round-delete class="text-icon" />
                </template>
                批量删除
              </AButton>
            </APopconfirm>
          </template>
        </TableHeaderOperation>
      </template>

      <ATable
        row-key="id"
        :row-selection="rowSelection"
        size="small"
        :columns="columns"
        :data-source="data"
        :loading="loading"
        :scroll="{ x: tableScrollX }"
        :pagination="mobilePagination"
        class="h-full"
      >
          <template #bodyCell="{ column, record, index }">
            <template v-if="column.key === 'index'">
              {{ index + 1 }}
            </template>
            <template v-else-if="column.key === 'enabled'">
              <ATag :color="toFeature(record).enabled ? 'success' : 'default'">{{
                toFeature(record).enabled ? "启用" : "停用"
              }}</ATag>
            </template>
            <template v-else-if="column.key === 'description'">
              <ATypographyText type="secondary">{{
                toFeature(record).description || "-"
              }}</ATypographyText>
            </template>
            <template v-else-if="column.key === 'updated_at'">
              {{ formatDateTime(toFeature(record).updated_at) }}
            </template>
            <template v-else-if="column.key === 'created_at'">
              {{ formatDateTime(toFeature(record).created_at) }}
            </template>
            <template v-else-if="column.key === 'operate'">
              <div class="flex-center justify-end gap-6px">
                <AButton type="primary" ghost size="small" @click="openEditModal(toFeature(record))"
                  >编辑</AButton
                >
                <APopconfirm
                  title="确定删除该功能？已被套餐使用的功能不能删除"
                  @confirm="removeFeature(toFeature(record))"
                >
                  <AButton danger ghost size="small">删除</AButton>
                </APopconfirm>
              </div>
            </template>
          </template>
      </ATable>
    </ACard>

    <AModal
      v-model:open="modalOpen"
      :title="modalTitle"
      :confirm-loading="submitting"
      destroy-on-hidden
      @ok="submitForm"
    >
      <AForm ref="formRef" layout="vertical" :model="formModel" :rules="formRules">
        <AFormItem label="功能编码" name="code">
          <AInput v-model:value="formModel.code" placeholder="例如：advanced-export" />
        </AFormItem>
        <AFormItem label="功能名称" name="name">
          <AInput v-model:value="formModel.name" placeholder="请输入功能名称" />
        </AFormItem>
        <AFormItem label="功能描述" name="description">
          <ATextarea
            v-model:value="formModel.description"
            :auto-size="{ minRows: 3, maxRows: 5 }"
            placeholder="请输入功能描述"
          />
        </AFormItem>
        <AFormItem label="状态" name="enabled">
          <ASwitch
            v-model:checked="formModel.enabled"
            checked-children="启用"
            un-checked-children="停用"
          />
        </AFormItem>
      </AForm>
    </AModal>
  </div>
</template>

// frontend/src/features/features/index.tsx
import { useCallback, useEffect, useMemo, useState } from 'react'
import { Loader2, Plus, RefreshCw, Search } from 'lucide-react'
import { toast } from 'sonner'
import {
  createFeature,
  deleteFeature,
  fetchFeatures,
  updateFeature,
} from '@/api/lykn'
import { formatDateTime, getErrorMessage } from '@/lib/lykn'
import type { FeaturePayload, FeatureRecord } from '@/types/api'
import { ConfirmDialog } from '@/components/confirm-dialog'
import { ConfigDrawer } from '@/components/config-drawer'
import { Header } from '@/components/layout/header'
import { Main } from '@/components/layout/main'
import { ProfileDropdown } from '@/components/profile-dropdown'
import { ThemeSwitch } from '@/components/theme-switch'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card'
import {
  Dialog,
  DialogContent,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import { Switch } from '@/components/ui/switch'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'
import { Textarea } from '@/components/ui/textarea'

const emptyForm: FeaturePayload = {
  code: '',
  name: '',
  description: '',
  enabled: true,
}

export function FeaturesPage() {
  const [loading, setLoading] = useState(true)
  const [rows, setRows] = useState<FeatureRecord[]>([])
  const [keyword, setKeyword] = useState('')
  const [enabledFilter, setEnabledFilter] = useState<string>('all')

  const [modalOpen, setModalOpen] = useState(false)
  const [submitting, setSubmitting] = useState(false)
  const [editing, setEditing] = useState<FeatureRecord | null>(null)
  const [form, setForm] = useState<FeaturePayload>(emptyForm)

  const [deleteTarget, setDeleteTarget] = useState<FeatureRecord | null>(null)
  const [deleting, setDeleting] = useState(false)

  const load = useCallback(async () => {
    setLoading(true)
    try {
      setRows(await fetchFeatures())
    } catch (error) {
      toast.error(getErrorMessage(error, '加载功能列表失败'))
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => {
    void load()
  }, [load])

  const filtered = useMemo(() => {
    const q = keyword.trim().toLowerCase()
    return rows.filter((item) => {
      const matchKeyword =
        !q ||
        item.code.toLowerCase().includes(q) ||
        item.name.toLowerCase().includes(q) ||
        item.description.toLowerCase().includes(q)
      const matchEnabled =
        enabledFilter === 'all' || String(item.enabled) === enabledFilter
      return matchKeyword && matchEnabled
    })
  }, [rows, keyword, enabledFilter])

  function openCreate() {
    setEditing(null)
    setForm(emptyForm)
    setModalOpen(true)
  }

  function openEdit(record: FeatureRecord) {
    setEditing(record)
    setForm({
      code: record.code,
      name: record.name,
      description: record.description,
      enabled: record.enabled,
    })
    setModalOpen(true)
  }

  async function submitForm() {
    if (!form.code.trim() || !form.name.trim()) {
      toast.error('请填写功能编码和名称')
      return
    }
    setSubmitting(true)
    try {
      const payload: FeaturePayload = {
        code: form.code.trim(),
        name: form.name.trim(),
        description: form.description.trim(),
        enabled: form.enabled,
      }
      if (editing) {
        await updateFeature(editing.id, payload)
        toast.success('功能已更新')
      } else {
        await createFeature(payload)
        toast.success('功能已创建')
      }
      setModalOpen(false)
      await load()
    } catch (error) {
      toast.error(getErrorMessage(error))
    } finally {
      setSubmitting(false)
    }
  }

  async function confirmDelete() {
    if (!deleteTarget) return
    setDeleting(true)
    try {
      await deleteFeature(deleteTarget.id)
      toast.success('功能已删除')
      setDeleteTarget(null)
      await load()
    } catch (error) {
      toast.error(getErrorMessage(error, '删除功能失败'))
    } finally {
      setDeleting(false)
    }
  }

  return (
    <>
      <Header>
        <div className='ms-auto flex items-center space-x-2'>
          <ThemeSwitch />
          <ConfigDrawer />
          <ProfileDropdown />
        </div>
      </Header>

      <Main>
        <div className='mb-4 flex flex-wrap items-center justify-between gap-3'>
          <div>
            <h1 className='text-2xl font-bold tracking-tight'>功能管理</h1>
            <p className='text-muted-foreground'>定义可授权的功能点</p>
          </div>
          <div className='flex items-center gap-2'>
            <Button variant='outline' size='sm' onClick={() => void load()}>
              <RefreshCw className={loading ? 'animate-spin' : ''} />
              刷新
            </Button>
            <Button size='sm' onClick={openCreate}>
              <Plus />
              新建功能
            </Button>
          </div>
        </div>

        <Card className='mb-4'>
          <CardContent className='flex flex-wrap gap-3 pt-6'>
            <div className='relative min-w-[220px] flex-1'>
              <Search className='absolute start-2.5 top-2.5 size-4 text-muted-foreground' />
              <Input
                className='ps-8'
                placeholder='搜索编码 / 名称 / 描述'
                value={keyword}
                onChange={(e) => setKeyword(e.target.value)}
              />
            </div>
            <Select value={enabledFilter} onValueChange={setEnabledFilter}>
              <SelectTrigger className='w-[140px]'>
                <SelectValue placeholder='状态' />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value='all'>全部状态</SelectItem>
                <SelectItem value='true'>启用</SelectItem>
                <SelectItem value='false'>停用</SelectItem>
              </SelectContent>
            </Select>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>功能列表</CardTitle>
            <CardDescription>共 {filtered.length} 个功能</CardDescription>
          </CardHeader>
          <CardContent className='overflow-x-auto'>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>功能</TableHead>
                  <TableHead>编码</TableHead>
                  <TableHead>状态</TableHead>
                  <TableHead>描述</TableHead>
                  <TableHead>更新时间</TableHead>
                  <TableHead className='text-end'>操作</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {loading ? (
                  <TableRow>
                    <TableCell colSpan={6} className='h-24 text-center'>
                      <Loader2 className='mx-auto animate-spin' />
                    </TableCell>
                  </TableRow>
                ) : filtered.length === 0 ? (
                  <TableRow>
                    <TableCell colSpan={6} className='h-24 text-center text-muted-foreground'>
                      暂无功能
                    </TableCell>
                  </TableRow>
                ) : (
                  filtered.map((record) => (
                    <TableRow key={record.id}>
                      <TableCell className='font-medium'>{record.name}</TableCell>
                      <TableCell className='font-mono text-sm'>{record.code}</TableCell>
                      <TableCell>
                        <Badge variant={record.enabled ? 'default' : 'secondary'}>
                          {record.enabled ? '启用' : '停用'}
                        </Badge>
                      </TableCell>
                      <TableCell className='max-w-[260px] truncate text-muted-foreground'>
                        {record.description || '-'}
                      </TableCell>
                      <TableCell>{formatDateTime(record.updated_at)}</TableCell>
                      <TableCell className='text-end'>
                        <div className='flex justify-end gap-1'>
                          <Button size='sm' variant='outline' onClick={() => openEdit(record)}>
                            编辑
                          </Button>
                          <Button
                            size='sm'
                            variant='destructive'
                            onClick={() => setDeleteTarget(record)}
                          >
                            删除
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                  ))
                )}
              </TableBody>
            </Table>
          </CardContent>
        </Card>
      </Main>

      <Dialog open={modalOpen} onOpenChange={setModalOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>{editing ? '编辑功能' : '新建功能'}</DialogTitle>
          </DialogHeader>
          <div className='grid gap-4 py-2'>
            <div className='grid gap-2'>
              <Label>功能编码</Label>
              <Input
                value={form.code}
                onChange={(e) => setForm((s) => ({ ...s, code: e.target.value }))}
                placeholder='例如：advanced-export'
              />
            </div>
            <div className='grid gap-2'>
              <Label>功能名称</Label>
              <Input
                value={form.name}
                onChange={(e) => setForm((s) => ({ ...s, name: e.target.value }))}
                placeholder='请输入功能名称'
              />
            </div>
            <div className='grid gap-2'>
              <Label>功能描述</Label>
              <Textarea
                value={form.description}
                onChange={(e) => setForm((s) => ({ ...s, description: e.target.value }))}
                placeholder='请输入功能描述'
              />
            </div>
            <div className='flex items-center justify-between rounded-md border p-3'>
              <div>
                <div className='text-sm font-medium'>启用状态</div>
                <div className='text-xs text-muted-foreground'>停用后不可被新套餐选择</div>
              </div>
              <Switch
                checked={form.enabled}
                onCheckedChange={(enabled) => setForm((s) => ({ ...s, enabled }))}
              />
            </div>
          </div>
          <DialogFooter>
            <Button variant='outline' onClick={() => setModalOpen(false)}>
              取消
            </Button>
            <Button disabled={submitting} onClick={() => void submitForm()}>
              {submitting && <Loader2 className='animate-spin' />}
              保存
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>

      <ConfirmDialog
        open={!!deleteTarget}
        onOpenChange={(open) => !open && setDeleteTarget(null)}
        title='删除功能'
        desc='确定删除该功能？已被套餐使用的功能不能删除。'
        confirmText={deleting ? '删除中...' : '删除'}
        destructive
        isLoading={deleting}
        handleConfirm={() => void confirmDelete()}
      />
    </>
  )
}
