// frontend/src/features/plans/index.tsx
import { useCallback, useEffect, useMemo, useState } from 'react'
import { Loader2, Plus, RefreshCw, Search } from 'lucide-react'
import { toast } from 'sonner'
import {
  createPlan,
  deletePlan,
  fetchFeatures,
  fetchPlans,
  updatePlan,
} from '@/api/lykn'
import { formatDateTime, getErrorMessage } from '@/lib/lykn'
import type { FeatureRecord, PlanPayload, PlanRecord } from '@/types/api'
import { ConfirmDialog } from '@/components/confirm-dialog'
import { FieldLabelTip } from '@/components/field-label-tip'
import { ConfigDrawer } from '@/components/config-drawer'
import { Header } from '@/components/layout/header'
import { Main } from '@/components/layout/main'
import { ProfileDropdown } from '@/components/profile-dropdown'
import { ThemeSwitch } from '@/components/theme-switch'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card'
import { Checkbox } from '@/components/ui/checkbox'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import {
  Sheet,
  SheetContent,
  SheetFooter,
  SheetHeader,
  SheetTitle,
} from '@/components/ui/sheet'
import { Switch } from '@/components/ui/switch'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'
import { Textarea } from '@/components/ui/textarea'

const emptyForm: PlanPayload = {
  code: '',
  name: '',
  description: '',
  feature_ids: [],
  max_users: 0,
  max_devices: 1,
  enabled: true,
}

export function PlansPage() {
  const [loading, setLoading] = useState(true)
  const [rows, setRows] = useState<PlanRecord[]>([])
  const [features, setFeatures] = useState<FeatureRecord[]>([])
  const [keyword, setKeyword] = useState('')
  const [enabledFilter, setEnabledFilter] = useState<string>('all')

  const [drawerOpen, setDrawerOpen] = useState(false)
  const [submitting, setSubmitting] = useState(false)
  const [editing, setEditing] = useState<PlanRecord | null>(null)
  const [form, setForm] = useState<PlanPayload>(emptyForm)

  const [deleteTarget, setDeleteTarget] = useState<PlanRecord | null>(null)
  const [deleting, setDeleting] = useState(false)

  const load = useCallback(async () => {
    setLoading(true)
    try {
      const [planRows, featureRows] = await Promise.all([fetchPlans(), fetchFeatures()])
      setRows(planRows)
      setFeatures(featureRows)
    } catch (error) {
      toast.error(getErrorMessage(error, '加载套餐失败'))
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => {
    void load()
  }, [load])

  const filtered = useMemo(() => {
    const q = keyword.trim().toLowerCase()
    return rows.filter((item) => {
      const matchKeyword =
        !q ||
        item.code.toLowerCase().includes(q) ||
        item.name.toLowerCase().includes(q) ||
        item.description.toLowerCase().includes(q)
      const matchEnabled =
        enabledFilter === 'all' || String(item.enabled) === enabledFilter
      return matchKeyword && matchEnabled
    })
  }, [rows, keyword, enabledFilter])

  function openCreate() {
    setEditing(null)
    setForm(emptyForm)
    setDrawerOpen(true)
  }

  function openEdit(record: PlanRecord) {
    setEditing(record)
    setForm({
      code: record.code,
      name: record.name,
      description: record.description,
      feature_ids: record.features.map((item) => item.id),
      max_users: record.max_users,
      max_devices: record.max_devices,
      enabled: record.enabled,
    })
    setDrawerOpen(true)
  }

  function toggleFeature(id: number, checked: boolean) {
    setForm((s) => ({
      ...s,
      feature_ids: checked
        ? [...s.feature_ids, id]
        : s.feature_ids.filter((item) => item !== id),
    }))
  }

  async function submitForm() {
    if (!form.code.trim() || !form.name.trim()) {
      toast.error('请填写套餐编码和名称')
      return
    }
    setSubmitting(true)
    try {
      const payload: PlanPayload = {
        ...form,
        code: form.code.trim(),
        name: form.name.trim(),
        description: form.description.trim(),
        max_users: Number(form.max_users) || 0,
        max_devices: Number(form.max_devices) || 0,
      }
      if (editing) {
        await updatePlan(editing.id, payload)
        toast.success('套餐已更新')
      } else {
        await createPlan(payload)
        toast.success('套餐已创建')
      }
      setDrawerOpen(false)
      await load()
    } catch (error) {
      toast.error(getErrorMessage(error))
    } finally {
      setSubmitting(false)
    }
  }

  async function confirmDelete() {
    if (!deleteTarget) return
    setDeleting(true)
    try {
      await deletePlan(deleteTarget.id)
      toast.success('套餐已删除')
      setDeleteTarget(null)
      await load()
    } catch (error) {
      toast.error(getErrorMessage(error, '删除套餐失败'))
    } finally {
      setDeleting(false)
    }
  }

  return (
    <>
      <Header>
        <div className='ms-auto flex items-center space-x-2'>
          <ThemeSwitch />
          <ConfigDrawer />
          <ProfileDropdown />
        </div>
      </Header>

      <Main>
        <div className='mb-4 flex flex-wrap items-center justify-between gap-3'>
          <div>
            <h1 className='text-2xl font-bold tracking-tight'>套餐管理</h1>
            <p className='text-muted-foreground'>组合功能与额度，供 License 签发使用</p>
          </div>
          <div className='flex items-center gap-2'>
            <Button variant='outline' size='sm' onClick={() => void load()}>
              <RefreshCw className={loading ? 'animate-spin' : ''} />
              刷新
            </Button>
            <Button size='sm' onClick={openCreate}>
              <Plus />
              新建套餐
            </Button>
          </div>
        </div>

        <Card className='mb-4'>
          <CardContent className='flex flex-wrap gap-3 pt-6'>
            <div className='relative min-w-[220px] flex-1'>
              <Search className='absolute start-2.5 top-2.5 size-4 text-muted-foreground' />
              <Input
                className='ps-8'
                placeholder='搜索编码 / 名称 / 描述'
                value={keyword}
                onChange={(e) => setKeyword(e.target.value)}
              />
            </div>
            <Select value={enabledFilter} onValueChange={setEnabledFilter}>
              <SelectTrigger className='w-[140px]'>
                <SelectValue placeholder='状态' />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value='all'>全部状态</SelectItem>
                <SelectItem value='true'>启用</SelectItem>
                <SelectItem value='false'>停用</SelectItem>
              </SelectContent>
            </Select>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>套餐列表</CardTitle>
            <CardDescription>共 {filtered.length} 个套餐</CardDescription>
          </CardHeader>
          <CardContent className='overflow-x-auto'>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>套餐</TableHead>
                  <TableHead>编码</TableHead>
                  <TableHead>状态</TableHead>
                  <TableHead>功能</TableHead>
                  <TableHead>额度</TableHead>
                  <TableHead>更新时间</TableHead>
                  <TableHead className='text-end'>操作</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {loading ? (
                  <TableRow>
                    <TableCell colSpan={7} className='h-24 text-center'>
                      <Loader2 className='mx-auto animate-spin' />
                    </TableCell>
                  </TableRow>
                ) : filtered.length === 0 ? (
                  <TableRow>
                    <TableCell colSpan={7} className='h-24 text-center text-muted-foreground'>
                      暂无套餐
                    </TableCell>
                  </TableRow>
                ) : (
                  filtered.map((record) => (
                    <TableRow key={record.id}>
                      <TableCell className='font-medium'>{record.name}</TableCell>
                      <TableCell className='font-mono text-sm'>{record.code}</TableCell>
                      <TableCell>
                        <Badge variant={record.enabled ? 'default' : 'secondary'}>
                          {record.enabled ? '启用' : '停用'}
                        </Badge>
                      </TableCell>
                      <TableCell>
                        <div className='flex max-w-[260px] flex-wrap gap-1'>
                          {record.features.length ? (
                            record.features.map((item) => (
                              <Badge key={item.id} variant='outline'>
                                {item.name}
                              </Badge>
                            ))
                          ) : (
                            <span className='text-muted-foreground'>未绑定</span>
                          )}
                        </div>
                      </TableCell>
                      <TableCell>
                        用户 {record.max_users || '不限'} / 设备 {record.max_devices || '-'}
                      </TableCell>
                      <TableCell>{formatDateTime(record.updated_at)}</TableCell>
                      <TableCell className='text-end'>
                        <div className='flex justify-end gap-1'>
                          <Button size='sm' variant='outline' onClick={() => openEdit(record)}>
                            编辑
                          </Button>
                          <Button
                            size='sm'
                            variant='destructive'
                            onClick={() => setDeleteTarget(record)}
                          >
                            删除
                          </Button>
                        </div>
                      </TableCell>
                    </TableRow>
                  ))
                )}
              </TableBody>
            </Table>
          </CardContent>
        </Card>
      </Main>

      <Sheet open={drawerOpen} onOpenChange={setDrawerOpen}>
        <SheetContent className='w-full overflow-y-auto sm:max-w-lg'>
          <SheetHeader>
            <SheetTitle>{editing ? '编辑套餐' : '新建套餐'}</SheetTitle>
          </SheetHeader>
          <div className='grid gap-4 px-4 py-2'>
            <div className='grid gap-2'>
              <Label>套餐编码</Label>
              <Input
                value={form.code}
                onChange={(e) => setForm((s) => ({ ...s, code: e.target.value }))}
                placeholder='例如：pro'
              />
            </div>
            <div className='grid gap-2'>
              <Label>套餐名称</Label>
              <Input
                value={form.name}
                onChange={(e) => setForm((s) => ({ ...s, name: e.target.value }))}
                placeholder='请输入套餐名称'
              />
            </div>
            <div className='grid gap-2'>
              <Label>套餐描述</Label>
              <Textarea
                value={form.description}
                onChange={(e) => setForm((s) => ({ ...s, description: e.target.value }))}
                placeholder='请输入套餐描述'
              />
            </div>
            <div className='grid gap-2'>
              <Label>包含功能</Label>
              <div className='max-h-48 space-y-2 overflow-y-auto rounded-md border p-3'>
                {features.length === 0 ? (
                  <p className='text-sm text-muted-foreground'>暂无功能，请先创建功能</p>
                ) : (
                  features.map((item) => (
                    <label key={item.id} className='flex items-center gap-2 text-sm'>
                      <Checkbox
                        checked={form.feature_ids.includes(item.id)}
                        disabled={!item.enabled && !form.feature_ids.includes(item.id)}
                        onCheckedChange={(checked) =>
                          toggleFeature(item.id, checked === true)
                        }
                      />
                      <span>
                        {item.name}
                        <span className='ms-1 text-muted-foreground'>· {item.code}</span>
                        {!item.enabled && (
                          <span className='ms-1 text-xs text-muted-foreground'>(已停用)</span>
                        )}
                      </span>
                    </label>
                  ))
                )}
              </div>
            </div>
            <div className='grid grid-cols-2 gap-3'>
              <div className='grid gap-2'>
                <FieldLabelTip tip='0 表示不限制用户数'>用户额度</FieldLabelTip>
                <Input
                  type='number'
                  min={0}
                  value={form.max_users}
                  onChange={(e) =>
                    setForm((s) => ({ ...s, max_users: Number(e.target.value) }))
                  }
                />
              </div>
              <div className='grid gap-2'>
                <Label>设备额度</Label>
                <Input
                  type='number'
                  min={1}
                  value={form.max_devices}
                  onChange={(e) =>
                    setForm((s) => ({ ...s, max_devices: Number(e.target.value) }))
                  }
                />
              </div>
            </div>
            <div className='flex items-center justify-between rounded-md border p-3'>
              <div>
                <div className='text-sm font-medium'>启用状态</div>
                <div className='text-xs text-muted-foreground'>停用后不可用于签发</div>
              </div>
              <Switch
                checked={form.enabled}
                onCheckedChange={(enabled) => setForm((s) => ({ ...s, enabled }))}
              />
            </div>
          </div>
          <SheetFooter>
            <Button variant='outline' onClick={() => setDrawerOpen(false)}>
              取消
            </Button>
            <Button disabled={submitting} onClick={() => void submitForm()}>
              {submitting && <Loader2 className='animate-spin' />}
              保存
            </Button>
          </SheetFooter>
        </SheetContent>
      </Sheet>

      <ConfirmDialog
        open={!!deleteTarget}
        onOpenChange={(open) => !open && setDeleteTarget(null)}
        title='删除套餐'
        desc='确定删除该套餐？'
        confirmText={deleting ? '删除中...' : '删除'}
        destructive
        isLoading={deleting}
        handleConfirm={() => void confirmDelete()}
      />
    </>
  )
}

// frontend/src/views/plans/index.vue
<script setup lang="ts">
import { computed, reactive, ref } from "vue";
import { useBoolean } from "@sa/hooks";
import { useAntdvForm } from "@/hooks/common/form";
import { useAntdvPaginatedTable, useTableOperate } from "@/hooks/common/table";
import { createPlan, deletePlan, fetchFeatures, fetchPlans, updatePlan } from "@/service/api";
import { formatDateTime, getServiceErrorMessage, unwrapFlatData } from "@/utils/lykn";

const searchModel = reactive({
  keyword: "",
  enabled: undefined as "true" | "false" | undefined,
});

const { formRef, validate, restoreValidation } = useAntdvForm();
const paginationParams = reactive({
  current: 1,
  size: 10,
});
const tableScrollX = 1504;

const drawerOpen = ref(false);
const submitting = ref(false);
const operateType = ref<AntdvUI.TableOperateType>("add");
const editingId = ref<number>();
const features = ref<Api.Lykn.FeatureRecord[]>([]);
const featureLoading = ref(false);

const formModel = reactive<Api.Lykn.PlanPayload>({
  code: "",
  name: "",
  description: "",
  feature_ids: [],
  max_users: 0,
  max_devices: 1,
  enabled: true,
});

const enabledOptions = [
  { label: "启用", value: "true" },
  { label: "停用", value: "false" },
];

const searchItems = computed(() => [
  { key: "keyword", label: "关键词", placeholder: "套餐编码 / 名称 / 描述" },
  {
    key: "enabled",
    label: "状态",
    type: "select" as const,
    placeholder: "请选择状态",
    options: enabledOptions,
  },
]);

const featureOptions = computed(() =>
  features.value.map((item) => ({
    label: `${item.name} · ${item.code}`,
    value: item.id,
    disabled: !item.enabled,
  })),
);

const selectedFeatures = computed(() =>
  features.value.filter((item) => formModel.feature_ids.includes(item.id)),
);

const formRules = {
  code: [{ required: true, message: "请输入套餐编码" }],
  name: [{ required: true, message: "请输入套餐名称" }],
  max_devices: [{ required: true, message: "请输入设备额度" }],
};

const { loading, data, columns, columnChecks, getData, getDataByPage, mobilePagination } =
  useAntdvPaginatedTable({
    api: fetchPlans,
    transform: (response) => {
      const records = unwrapFlatData(response, "加载套餐列表失败") as Api.Lykn.PlanRecord[];
      const keyword = searchModel.keyword.trim().toLowerCase();

      const filteredRecords = records.filter((item) => {
        const matchKeyword =
          !keyword ||
          item.code.toLowerCase().includes(keyword) ||
          item.name.toLowerCase().includes(keyword) ||
          item.description.toLowerCase().includes(keyword);
        const matchEnabled =
          searchModel.enabled === undefined || String(item.enabled) === searchModel.enabled;

        return matchKeyword && matchEnabled;
      });

      return {
        data: filteredRecords,
        pageNum: paginationParams.current,
        pageSize: paginationParams.size,
        total: filteredRecords.length,
      };
    },
    onPaginationParamsChange: (params) => {
      paginationParams.current = params.current || 1;
      paginationParams.size = params.pageSize || 10;
    },
    columns: () => [
      { key: "index", title: "序号", align: "center", width: 64, fixed: "left" },
      { key: "name", dataIndex: "name", title: "套餐", align: "left", width: 180, fixed: "left" },
      { key: "code", dataIndex: "code", title: "编码", align: "left", width: 160 },
      { key: "enabled", dataIndex: "enabled", title: "状态", align: "center", width: 100 },
      { key: "features", dataIndex: "features", title: "功能", align: "left", width: 260 },
      { key: "limits", title: "额度", align: "center", width: 160 },
      { key: "description", dataIndex: "description", title: "描述", align: "left", width: 260 },
      {
        key: "updated_at",
        dataIndex: "updated_at",
        title: "更新时间",
        align: "center",
        width: 180,
      },
      { key: "operate", title: "操作", align: "center", width: 140, fixed: "right" },
    ],
  });

const { checkedRowKeys, onBatchDeleted } = useTableOperate(data, "id", getData);
const { bool: batchDeleting, setBool: setBatchDeleting } = useBoolean();
const rowSelection = computed(() => ({
  fixed: true,
  selectedRowKeys: checkedRowKeys.value,
  onChange: (keys: (string | number)[]) => {
    checkedRowKeys.value = keys as string[];
  },
}));

const drawerTitle = computed(() => (operateType.value === "add" ? "新建套餐" : "编辑套餐"));

async function loadFeatures() {
  featureLoading.value = true;
  try {
    features.value = unwrapFlatData(await fetchFeatures(), "加载功能列表失败");
  } catch (error) {
    window.$message?.error(getServiceErrorMessage(error));
  } finally {
    featureLoading.value = false;
  }
}

function handleSearch() {
  getDataByPage();
}

function resetSearch() {
  searchModel.keyword = "";
  searchModel.enabled = undefined;
  getDataByPage();
}

function resetForm() {
  editingId.value = undefined;
  formModel.code = "";
  formModel.name = "";
  formModel.description = "";
  formModel.feature_ids = [];
  formModel.max_users = 0;
  formModel.max_devices = 1;
  formModel.enabled = true;
  void restoreValidation();
}

function openCreateDrawer() {
  resetForm();
  operateType.value = "add";
  drawerOpen.value = true;
}

function openEditDrawer(record: Api.Lykn.PlanRecord) {
  operateType.value = "edit";
  editingId.value = record.id;
  formModel.code = record.code;
  formModel.name = record.name;
  formModel.description = toPlan(record).description;
  formModel.feature_ids = toPlan(record).features.map((item) => item.id);
  formModel.max_users = toPlan(record).max_users;
  formModel.max_devices = toPlan(record).max_devices;
  formModel.enabled = toPlan(record).enabled;
  drawerOpen.value = true;
}

async function submitForm() {
  await validate();

  submitting.value = true;
  try {
    const payload: Api.Lykn.PlanPayload = {
      ...formModel,
      max_users: Number(formModel.max_users) || 0,
      max_devices: Number(formModel.max_devices) || 0,
    };

    if (operateType.value === "add") {
      unwrapFlatData(await createPlan(payload), "创建套餐失败");
      window.$message?.success("套餐已创建");
    } else if (editingId.value) {
      unwrapFlatData(await updatePlan(editingId.value, payload), "更新套餐失败");
      window.$message?.success("套餐已更新");
    }

    drawerOpen.value = false;
    await getDataByPage();
  } catch (error) {
    window.$message?.error(getServiceErrorMessage(error));
  } finally {
    submitting.value = false;
  }
}

function toPlan(record: unknown) {
  return record as Api.Lykn.PlanRecord;
}

async function handleBatchDelete() {
  setBatchDeleting(true);
  try {
    await Promise.all(checkedRowKeys.value.map((id) => deletePlan(Number(id))));
    await onBatchDeleted();
  } catch (error) {
    checkedRowKeys.value = [];
    window.$message?.error(getServiceErrorMessage(error, "批量删除套餐失败"));
    await getDataByPage();
  } finally {
    setBatchDeleting(false);
  }
}

async function removePlan(record: Api.Lykn.PlanRecord) {
  try {
    unwrapFlatData(await deletePlan(record.id), "删除套餐失败");
    window.$message?.success("套餐已删除");
    await getDataByPage();
  } catch (error) {
    window.$message?.error(getServiceErrorMessage(error));
  }
}

loadFeatures();
</script>

<template>
  <div class="min-h-500px flex-col-stretch gap-16px overflow-hidden lt-sm:overflow-auto">
    <QuerySearchForm
      v-model:model="searchModel"
      :items="searchItems"
      :loading="loading"
      @search="handleSearch"
      @reset="resetSearch"
    />

    <ACard
      title="套餐管理"
      variant="borderless"
      :body-style="{ flex: 1, overflow: 'hidden' }"
      class="flex-col-stretch sm:flex-1-hidden card-wrapper"
    >
      <template #extra>
        <TableHeaderOperation
          v-model:columns="columnChecks"
          :disabled-delete="checkedRowKeys.length === 0"
          :loading="loading"
          @refresh="getData"
        >
          <template #default>
            <AButton size="small" ghost type="primary" @click="openCreateDrawer">
              <template #icon>
                <icon-ic-round-plus class="text-icon" />
              </template>
              新建套餐
            </AButton>
            <APopconfirm title="确认删除吗？" @confirm="handleBatchDelete">
              <AButton
                size="small"
                ghost
                danger
                :disabled="checkedRowKeys.length === 0"
                :loading="batchDeleting"
              >
                <template #icon>
                  <icon-ic-round-delete class="text-icon" />
                </template>
                批量删除
              </AButton>
            </APopconfirm>
          </template>
        </TableHeaderOperation>
      </template>

      <ATable
        row-key="id"
        :row-selection="rowSelection"
        size="small"
        :columns="columns"
        :data-source="data"
        :loading="loading"
        :scroll="{ x: tableScrollX }"
        :pagination="mobilePagination"
        class="h-full"
      >
          <template #bodyCell="{ column, record, index }">
            <template v-if="column.key === 'index'">
              {{ index + 1 }}
            </template>
            <template v-else-if="column.key === 'enabled'">
              <ATag :color="toPlan(record).enabled ? 'success' : 'default'">{{
                toPlan(record).enabled ? "启用" : "停用"
              }}</ATag>
            </template>
            <template v-else-if="column.key === 'features'">
              <ASpace wrap>
                <ATag v-for="item in toPlan(record).features" :key="item.id" color="processing">{{
                  item.name
                }}</ATag>
                <ATypographyText v-if="!toPlan(record).features.length" type="secondary"
                  >未绑定</ATypographyText
                >
              </ASpace>
            </template>
            <template v-else-if="column.key === 'limits'">
              用户 {{ toPlan(record).max_users || "不限" }} / 设备
              {{ toPlan(record).max_devices || "-" }}
            </template>
            <template v-else-if="column.key === 'description'">
              <ATypographyText type="secondary">{{
                toPlan(record).description || "-"
              }}</ATypographyText>
            </template>
            <template v-else-if="column.key === 'updated_at'">
              {{ formatDateTime(toPlan(record).updated_at) }}
            </template>
            <template v-else-if="column.key === 'operate'">
              <div class="flex-center justify-end gap-6px">
                <AButton type="primary" ghost size="small" @click="openEditDrawer(toPlan(record))"
                  >编辑</AButton
                >
                <APopconfirm title="确定删除该套餐？" @confirm="removePlan(toPlan(record))">
                  <AButton danger ghost size="small">删除</AButton>
                </APopconfirm>
              </div>
            </template>
          </template>
      </ATable>
    </ACard>

    <ADrawer v-model:open="drawerOpen" :title="drawerTitle" :size="560" destroy-on-hidden>
      <template #extra>
        <ASpace>
          <AButton @click="drawerOpen = false">取消</AButton>
          <AButton type="primary" :loading="submitting" @click="submitForm">保存</AButton>
        </ASpace>
      </template>

      <AForm ref="formRef" layout="vertical" :model="formModel" :rules="formRules">
        <AFormItem label="套餐编码" name="code">
          <AInput v-model:value="formModel.code" placeholder="例如：pro" />
        </AFormItem>
        <AFormItem label="套餐名称" name="name">
          <AInput v-model:value="formModel.name" placeholder="请输入套餐名称" />
        </AFormItem>
        <AFormItem label="套餐描述" name="description">
          <ATextarea
            v-model:value="formModel.description"
            :auto-size="{ minRows: 3, maxRows: 5 }"
            placeholder="请输入套餐描述"
          />
        </AFormItem>
        <AFormItem label="包含功能" name="feature_ids">
          <ASelect
            v-model:value="formModel.feature_ids"
            mode="multiple"
            allow-clear
            :loading="featureLoading"
            :options="featureOptions"
            placeholder="请选择功能"
          />
        </AFormItem>
        <AFormItem v-if="selectedFeatures.length" label="已选功能">
          <ASpace wrap>
            <ATag v-for="item in selectedFeatures" :key="item.id" color="processing">{{
              item.name
            }}</ATag>
          </ASpace>
        </AFormItem>
        <AFormItem label="用户额度" name="max_users" extra="0 表示不限制用户数">
          <AInputNumber v-model:value="formModel.max_users" class="w-full" :min="0" />
        </AFormItem>
        <AFormItem label="设备额度" name="max_devices">
          <AInputNumber v-model:value="formModel.max_devices" class="w-full" :min="1" />
        </AFormItem>
        <AFormItem label="状态" name="enabled">
          <ASwitch
            v-model:checked="formModel.enabled"
            checked-children="启用"
            un-checked-children="停用"
          />
        </AFormItem>
      </AForm>
    </ADrawer>
  </div>
</template>
