// frontend/src/views/licenses/index.vue
<script setup lang="ts">
import { computed, reactive, ref, watch } from "vue";
import type { Dayjs } from "dayjs";
import { useAntdvForm } from "@/hooks/common/form";
import { useAntdvPaginatedTable } from "@/hooks/common/table";
import { fetchPlans, fetchProjectLicenses, issueLicense, downloadLicense } from "@/service/api";
import { useAuthStore } from "@/store/modules/auth";
import {
  formatDateTime,
  formatPeriod,
  getLicenseState,
  getServiceErrorMessage,
  saveBlobFile,
  unwrapFlatData,
} from "@/utils/lykn";

const authStore = useAuthStore();

const searchModel = reactive({
  projectId: null as number | null,
  keyword: "",
  state: undefined as "active" | "upcoming" | "expired" | undefined,
});

const { formRef, validate, restoreValidation } = useAntdvForm();
const paginationParams = reactive({
  current: 1,
  size: 10,
});
const tableScrollX = 1734;
const plans = ref<Api.Lykn.PlanRecord[]>([]);
const planLoading = ref(false);
const issuing = ref(false);
const drawerOpen = ref(false);
const detailOpen = ref(false);
const detailRecord = ref<Api.Lykn.LicenseRecord>();
const downloadingId = ref<number>();

const formModel = reactive({
  subjectName: "",
  subjectEmail: "",
  subjectOrg: "",
  planId: undefined as number | undefined,
  validRange: null as [Dayjs, Dayjs] | null,
  hardwareKeys: [] as Array<keyof Api.Lykn.LicenseHardwarePayload>,
  hostname: "",
  cpu_id: "",
  disk_serial: "",
  mac_addresses: "",
});

const stateOptions = [
  { label: "生效中", value: "active" },
  { label: "未开始", value: "upcoming" },
  { label: "已过期", value: "expired" },
];

const searchItems = computed(() => [
  { key: "projectId", label: "项目", type: "select" as const, placeholder: "请选择项目" },
  { key: "keyword", label: "关键词", placeholder: "客户 / 邮箱 / UUID / 套餐" },
  {
    key: "state",
    label: "有效性",
    type: "select" as const,
    placeholder: "请选择有效性",
    options: stateOptions,
  },
]);

const hardwareOptions = [
  { label: "主机名", value: "hostname" },
  { label: "CPU ID", value: "cpu_id" },
  { label: "磁盘序列号", value: "disk_serial" },
  { label: "MAC 地址", value: "mac_addresses" },
];

const formRules = {
  subjectName: [{ required: true, message: "请输入授权对象" }],
  planId: [{ required: true, message: "请选择套餐" }],
  validRange: [{ required: true, message: "请选择有效期" }],
};

const projectOptions = computed(() =>
  authStore.projects.map((project) => ({
    label: `${project.name} · ${project.key_bits} bit`,
    value: project.id,
  })),
);

const enabledPlans = computed(() => plans.value.filter((item) => item.enabled));
const planOptions = computed(() =>
  enabledPlans.value.map((item) => ({ label: `${item.name} · ${item.code}`, value: item.id })),
);
const selectedPlan = computed(() => plans.value.find((item) => item.id === formModel.planId));

const { loading, data, columns, columnChecks, getData, getDataByPage, mobilePagination } =
  useAntdvPaginatedTable({
    api: () => {
      if (!authStore.selectedProjectId) {
        return Promise.resolve({ data: [], error: null, response: {} as any });
      }

      return fetchProjectLicenses(authStore.selectedProjectId);
    },
    transform: (response) => {
      const records = !response.error && response.data ? response.data : [];
      const keyword = searchModel.keyword.trim().toLowerCase();

      const filteredRecords = records.filter((item) => {
        const matchKeyword =
          !keyword ||
          item.uuid.toLowerCase().includes(keyword) ||
          item.subject_name.toLowerCase().includes(keyword) ||
          item.subject_email.toLowerCase().includes(keyword) ||
          item.subject_org.toLowerCase().includes(keyword) ||
          item.plan.toLowerCase().includes(keyword) ||
          item.plan_name.toLowerCase().includes(keyword);
        const matchState = !searchModel.state || getLicenseState(item) === searchModel.state;

        return matchKeyword && matchState;
      });

      return {
        data: filteredRecords,
        pageNum: paginationParams.current,
        pageSize: paginationParams.size,
        total: filteredRecords.length,
      };
    },
    onPaginationParamsChange: (params) => {
      paginationParams.current = params.current || 1;
      paginationParams.size = params.pageSize || 10;
    },
    columns: () => [
      { key: "index", title: "序号", align: "center", width: 64, fixed: "left" },
      { key: "subject", title: "授权对象", align: "left", width: 220, fixed: "left" },
      { key: "uuid", dataIndex: "uuid", title: "UUID", align: "left", width: 280 },
      { key: "plan", title: "套餐", align: "left", width: 180 },
      { key: "state", title: "状态", align: "center", width: 100 },
      { key: "period", title: "有效期", align: "center", width: 300 },
      { key: "features", title: "功能", align: "left", width: 260 },
      {
        key: "created_at",
        dataIndex: "created_at",
        title: "签发时间",
        align: "center",
        width: 180,
      },
      { key: "operate", title: "操作", align: "center", width: 150, fixed: "right" },
    ],
  });

function stateText(record: Api.Lykn.LicenseRecord) {
  const state = getLicenseState(record);
  if (state === "active") return "生效中";
  if (state === "upcoming") return "未开始";
  if (state === "expired") return "已过期";
  return "未知";
}

function stateColor(record: Api.Lykn.LicenseRecord) {
  const state = getLicenseState(record);
  if (state === "active") return "success";
  if (state === "upcoming") return "processing";
  if (state === "expired") return "error";
  return "default";
}

async function loadPlans() {
  planLoading.value = true;
  try {
    plans.value = unwrapFlatData(await fetchPlans(), "加载套餐列表失败");
  } catch (error) {
    window.$message?.error(getServiceErrorMessage(error));
  } finally {
    planLoading.value = false;
  }
}

function handleSearch() {
  getDataByPage();
}

function resetSearch() {
  searchModel.projectId = authStore.selectedProjectId || null;
  searchModel.keyword = "";
  searchModel.state = undefined;
  getDataByPage();
}

function resetForm() {
  formModel.subjectName = "";
  formModel.subjectEmail = "";
  formModel.subjectOrg = "";
  formModel.planId = enabledPlans.value[0]?.id;
  formModel.validRange = null;
  formModel.hardwareKeys = [];
  formModel.hostname = "";
  formModel.cpu_id = "";
  formModel.disk_serial = "";
  formModel.mac_addresses = "";
  void restoreValidation();
}

function openIssueDrawer() {
  if (!authStore.selectedProjectId) {
    window.$message?.warning("请先选择项目");
    return;
  }

  if (!enabledPlans.value.length) {
    window.$message?.warning("请先创建并启用套餐");
    return;
  }

  resetForm();
  drawerOpen.value = true;
}

function hasHardwareKey(key: keyof Api.Lykn.LicenseHardwarePayload) {
  return formModel.hardwareKeys.includes(key);
}

function getHardwarePayload() {
  const payload: Api.Lykn.LicenseHardwarePayload = {};

  if (hasHardwareKey("hostname")) payload.hostname = formModel.hostname.trim();
  if (hasHardwareKey("cpu_id")) payload.cpu_id = formModel.cpu_id.trim();
  if (hasHardwareKey("disk_serial")) payload.disk_serial = formModel.disk_serial.trim();
  if (hasHardwareKey("mac_addresses")) {
    payload.mac_addresses = formModel.mac_addresses
      .split(",")
      .map((item) => item.trim())
      .filter(Boolean);
  }

  return payload;
}

async function submitIssue() {
  await validate();

  if (!authStore.selectedProjectId || !formModel.planId || !formModel.validRange) return;

  issuing.value = true;
  try {
    unwrapFlatData(
      await issueLicense(authStore.selectedProjectId, {
        subject: {
          name: formModel.subjectName.trim(),
          email: formModel.subjectEmail.trim(),
          organization: formModel.subjectOrg.trim(),
        },
        plan_id: formModel.planId,
        not_before: formModel.validRange[0].toISOString(),
        not_after: formModel.validRange[1].toISOString(),
        hardware: getHardwarePayload(),
      }),
      "签发 License 失败",
    );

    window.$message?.success("License 已签发");
    drawerOpen.value = false;
    await getDataByPage();
  } catch (error) {
    window.$message?.error(getServiceErrorMessage(error));
  } finally {
    issuing.value = false;
  }
}

async function download(record: Api.Lykn.LicenseRecord) {
  downloadingId.value = record.id;
  try {
    saveBlobFile(await downloadLicense(record.id));
  } catch (error) {
    window.$message?.error(getServiceErrorMessage(error, "下载 License 失败"));
  } finally {
    downloadingId.value = undefined;
  }
}

function showDetail(record: Api.Lykn.LicenseRecord) {
  detailRecord.value = record;
  detailOpen.value = true;
}

watch(
  () => authStore.selectedProjectId,
  (projectId) => {
    searchModel.projectId = projectId || null;
    getDataByPage();
  },
  { immediate: true },
);

authStore.loadProjects();
loadPlans();
</script>

<template>
  <div class="min-h-500px flex-col-stretch gap-16px overflow-hidden lt-sm:overflow-auto">
    <QuerySearchForm
      v-model:model="searchModel"
      :items="searchItems"
      :loading="loading"
      @search="handleSearch"
      @reset="resetSearch"
    >
      <template #projectId>
        <ASelect
          v-model:value="authStore.selectedProjectId"
          allow-clear
          class="w-full"
          :loading="authStore.loadingProjects"
          :options="projectOptions"
          placeholder="请选择项目"
        />
      </template>
    </QuerySearchForm>

    <ACard
      title="License 管理"
      variant="borderless"
      :body-style="{ flex: 1, overflow: 'hidden' }"
      class="flex-col-stretch sm:flex-1-hidden card-wrapper"
    >
      <template #extra>
        <TableHeaderOperation v-model:columns="columnChecks" :loading="loading" @refresh="getData">
          <template #default>
            <AButton size="small" ghost type="primary" @click="openIssueDrawer">
              <template #icon>
                <icon-ic-round-plus class="text-icon" />
              </template>
              签发 License
            </AButton>
          </template>
        </TableHeaderOperation>
      </template>

      <ATable
        row-key="id"
        size="small"
        :columns="columns"
        :data-source="data"
        :loading="loading"
        :scroll="{ x: tableScrollX }"
        :pagination="mobilePagination"
        class="h-full"
      >
          <template #bodyCell="{ column, record, index }">
            <template v-if="column.key === 'index'">
              {{ index + 1 }}
            </template>
            <template v-else-if="column.key === 'subject'">
              <div class="flex-col gap-4px">
                <ATypographyText strong>{{ record.subject_name }}</ATypographyText>
                <ATypographyText type="secondary" class="text-12px">{{
                  record.subject_email || "-"
                }}</ATypographyText>
              </div>
            </template>
            <template v-else-if="column.key === 'uuid'">
              <ATypographyText copyable class="font-mono text-12px">{{
                record.uuid
              }}</ATypographyText>
            </template>
            <template v-else-if="column.key === 'plan'">
              {{ record.plan_name || record.plan || "-" }}
            </template>
            <template v-else-if="column.key === 'state'">
              <ATag :color="stateColor(record)">{{ stateText(record) }}</ATag>
            </template>
            <template v-else-if="column.key === 'period'">
              {{ formatPeriod(record.not_before, record.not_after) }}
            </template>
            <template v-else-if="column.key === 'features'">
              <ASpace wrap>
                <ATag v-for="item in record.features" :key="item">{{ item }}</ATag>
                <ATypographyText v-if="!record.features.length" type="secondary"
                  >未配置</ATypographyText
                >
              </ASpace>
            </template>
            <template v-else-if="column.key === 'created_at'">
              {{ formatDateTime(record.created_at) }}
            </template>
            <template v-else-if="column.key === 'operate'">
              <div class="flex-center justify-end gap-6px">
                <AButton type="primary" ghost size="small" @click="showDetail(record)"
                  >详情</AButton
                >
                <AButton
                  size="small"
                  :loading="downloadingId === record.id"
                  @click="download(record)"
                  >下载</AButton
                >
              </div>
            </template>
          </template>
      </ATable>
    </ACard>

    <ADrawer v-model:open="drawerOpen" title="签发 License" :size="640" destroy-on-hidden>
      <template #extra>
        <ASpace>
          <AButton @click="drawerOpen = false">取消</AButton>
          <AButton type="primary" :loading="issuing" @click="submitIssue">签发</AButton>
        </ASpace>
      </template>

      <AForm ref="formRef" layout="vertical" :model="formModel" :rules="formRules">
        <AFormItem label="授权对象" name="subjectName">
          <AInput v-model:value="formModel.subjectName" placeholder="请输入客户或组织名称" />
        </AFormItem>
        <AFormItem label="邮箱" name="subjectEmail">
          <AInput v-model:value="formModel.subjectEmail" placeholder="请输入邮箱" />
        </AFormItem>
        <AFormItem label="组织" name="subjectOrg">
          <AInput v-model:value="formModel.subjectOrg" placeholder="请输入组织" />
        </AFormItem>
        <AFormItem label="套餐" name="planId">
          <ASelect
            v-model:value="formModel.planId"
            :loading="planLoading"
            :options="planOptions"
            placeholder="请选择套餐"
          />
        </AFormItem>
        <AAlert v-if="selectedPlan" type="info" show-icon class="mb-16px">
          <template #message>
            功能 {{ selectedPlan.features.length }} 个，用户
            {{ selectedPlan.max_users || "不限" }}，设备 {{ selectedPlan.max_devices || "-" }}
          </template>
        </AAlert>
        <AFormItem label="有效期" name="validRange">
          <ARangePicker v-model:value="formModel.validRange" class="w-full" show-time />
        </AFormItem>
        <AFormItem label="硬件绑定">
          <ACheckboxGroup v-model:value="formModel.hardwareKeys" :options="hardwareOptions" />
        </AFormItem>
        <AFormItem v-if="hasHardwareKey('hostname')" label="主机名">
          <AInput v-model:value="formModel.hostname" placeholder="例如：office-mac" />
        </AFormItem>
        <AFormItem v-if="hasHardwareKey('cpu_id')" label="CPU ID">
          <AInput v-model:value="formModel.cpu_id" placeholder="例如：BFEBFBFF000906EA" />
        </AFormItem>
        <AFormItem v-if="hasHardwareKey('disk_serial')" label="磁盘序列号">
          <AInput v-model:value="formModel.disk_serial" placeholder="例如：DISK-SERIAL-001" />
        </AFormItem>
        <AFormItem v-if="hasHardwareKey('mac_addresses')" label="MAC 地址">
          <AInput v-model:value="formModel.mac_addresses" placeholder="多个地址用英文逗号分隔" />
        </AFormItem>
      </AForm>
    </ADrawer>

    <ADrawer v-model:open="detailOpen" title="License 详情" :size="560">
      <AEmpty v-if="!detailRecord" description="暂无详情" />
      <ADescriptions v-else :column="1" bordered size="small">
        <ADescriptionsItem label="UUID">
          <ATypographyText copyable class="font-mono text-12px">{{
            detailRecord.uuid
          }}</ATypographyText>
        </ADescriptionsItem>
        <ADescriptionsItem label="授权对象">{{ detailRecord.subject_name }}</ADescriptionsItem>
        <ADescriptionsItem label="邮箱">{{ detailRecord.subject_email || "-" }}</ADescriptionsItem>
        <ADescriptionsItem label="组织">{{ detailRecord.subject_org || "-" }}</ADescriptionsItem>
        <ADescriptionsItem label="套餐">{{
          detailRecord.plan_name || detailRecord.plan || "-"
        }}</ADescriptionsItem>
        <ADescriptionsItem label="有效期">{{
          formatPeriod(detailRecord.not_before, detailRecord.not_after)
        }}</ADescriptionsItem>
        <ADescriptionsItem label="额度">
          用户 {{ detailRecord.limits?.max_users || "不限" }} / 设备
          {{ detailRecord.limits?.max_devices || "-" }}
        </ADescriptionsItem>
        <ADescriptionsItem label="功能">
          <ASpace wrap>
            <ATag v-for="item in detailRecord.features" :key="item">{{ item }}</ATag>
            <ATypographyText v-if="!detailRecord.features.length" type="secondary"
              >未配置</ATypographyText
            >
          </ASpace>
        </ADescriptionsItem>
      </ADescriptions>
    </ADrawer>
  </div>
</template>

// frontend/src/features/licenses/index.tsx
import { useCallback, useEffect, useMemo, useState } from 'react'
import { Loader2, Plus, RefreshCw, Search } from 'lucide-react'
import { toast } from 'sonner'
import {
  downloadLicense,
  fetchPlans,
  fetchProjectLicenses,
  issueLicense,
} from '@/api/lykn'
import {
  formatDateTime,
  formatPeriod,
  getErrorMessage,
  getLicenseState,
  licenseStateText,
  saveBlobFile,
  toDatetimeLocalValue,
} from '@/lib/lykn'
import { useAuthStore } from '@/stores/auth-store'
import type {
  LicenseHardwarePayload,
  LicenseRecord,
  LicenseState,
  PlanRecord,
} from '@/types/api'
import { ConfigDrawer } from '@/components/config-drawer'
import { Header } from '@/components/layout/header'
import { Main } from '@/components/layout/main'
import { ProfileDropdown } from '@/components/profile-dropdown'
import { ThemeSwitch } from '@/components/theme-switch'
import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from '@/components/ui/card'
import { Checkbox } from '@/components/ui/checkbox'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from '@/components/ui/select'
import {
  Sheet,
  SheetContent,
  SheetFooter,
  SheetHeader,
  SheetTitle,
} from '@/components/ui/sheet'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '@/components/ui/table'

type HardwareKey = keyof LicenseHardwarePayload

type IssueForm = {
  subjectName: string
  subjectEmail: string
  subjectOrg: string
  planId?: number
  notBefore: string
  notAfter: string
  hardwareKeys: HardwareKey[]
  hostname: string
  cpu_id: string
  disk_serial: string
  mac_addresses: string
}

const hardwareOptions: { label: string; value: HardwareKey }[] = [
  { label: '主机名', value: 'hostname' },
  { label: 'CPU ID', value: 'cpu_id' },
  { label: '磁盘序列号', value: 'disk_serial' },
  { label: 'MAC 地址', value: 'mac_addresses' },
]

function defaultIssueForm(planId?: number): IssueForm {
  const now = new Date()
  const end = new Date(now)
  end.setFullYear(end.getFullYear() + 1)
  return {
    subjectName: '',
    subjectEmail: '',
    subjectOrg: '',
    planId,
    notBefore: toDatetimeLocalValue(now),
    notAfter: toDatetimeLocalValue(end),
    hardwareKeys: [],
    hostname: '',
    cpu_id: '',
    disk_serial: '',
    mac_addresses: '',
  }
}

function stateVariant(state: LicenseState): 'default' | 'secondary' | 'destructive' | 'outline' {
  if (state === 'active') return 'default'
  if (state === 'upcoming') return 'secondary'
  if (state === 'expired') return 'destructive'
  return 'outline'
}

export function LicensesPage() {
  const projects = useAuthStore((s) => s.auth.projects)
  const selectedProjectId = useAuthStore((s) => s.auth.selectedProjectId)
  const loadingProjects = useAuthStore((s) => s.auth.loadingProjects)
  const selectProject = useAuthStore((s) => s.auth.selectProject)
  const loadProjects = useAuthStore((s) => s.auth.loadProjects)

  const [loading, setLoading] = useState(false)
  const [rows, setRows] = useState<LicenseRecord[]>([])
  const [plans, setPlans] = useState<PlanRecord[]>([])
  const [keyword, setKeyword] = useState('')
  const [stateFilter, setStateFilter] = useState<string>('all')

  const [drawerOpen, setDrawerOpen] = useState(false)
  const [issuing, setIssuing] = useState(false)
  const [form, setForm] = useState<IssueForm>(defaultIssueForm())

  const [detailOpen, setDetailOpen] = useState(false)
  const [detailRecord, setDetailRecord] = useState<LicenseRecord | null>(null)
  const [downloadingId, setDownloadingId] = useState<number>()

  const enabledPlans = useMemo(() => plans.filter((item) => item.enabled), [plans])
  const selectedPlan = useMemo(
    () => plans.find((item) => item.id === form.planId),
    [plans, form.planId]
  )

  const loadLicenses = useCallback(async () => {
    if (!selectedProjectId) {
      setRows([])
      return
    }
    setLoading(true)
    try {
      setRows(await fetchProjectLicenses(selectedProjectId))
    } catch (error) {
      toast.error(getErrorMessage(error, '加载 License 失败'))
    } finally {
      setLoading(false)
    }
  }, [selectedProjectId])

  const loadPlans = useCallback(async () => {
    try {
      setPlans(await fetchPlans())
    } catch (error) {
      toast.error(getErrorMessage(error, '加载套餐失败'))
    }
  }, [])

  useEffect(() => {
    void loadProjects()
    void loadPlans()
  }, [loadProjects, loadPlans])

  useEffect(() => {
    void loadLicenses()
  }, [loadLicenses])

  const filtered = useMemo(() => {
    const q = keyword.trim().toLowerCase()
    return rows.filter((item) => {
      const matchKeyword =
        !q ||
        item.uuid.toLowerCase().includes(q) ||
        item.subject_name.toLowerCase().includes(q) ||
        item.subject_email.toLowerCase().includes(q) ||
        item.subject_org.toLowerCase().includes(q) ||
        item.plan.toLowerCase().includes(q) ||
        item.plan_name.toLowerCase().includes(q)
      const state = getLicenseState(item)
      const matchState = stateFilter === 'all' || state === stateFilter
      return matchKeyword && matchState
    })
  }, [rows, keyword, stateFilter])

  function openIssueDrawer() {
    if (!selectedProjectId) {
      toast.warning('请先选择项目')
      return
    }
    if (!enabledPlans.length) {
      toast.warning('请先创建并启用套餐')
      return
    }
    setForm(defaultIssueForm(enabledPlans[0]?.id))
    setDrawerOpen(true)
  }

  function hasHardwareKey(key: HardwareKey) {
    return form.hardwareKeys.includes(key)
  }

  function toggleHardwareKey(key: HardwareKey, checked: boolean) {
    setForm((s) => ({
      ...s,
      hardwareKeys: checked
        ? [...s.hardwareKeys, key]
        : s.hardwareKeys.filter((item) => item !== key),
    }))
  }

  function getHardwarePayload(): LicenseHardwarePayload {
    const payload: LicenseHardwarePayload = {}
    if (hasHardwareKey('hostname')) payload.hostname = form.hostname.trim()
    if (hasHardwareKey('cpu_id')) payload.cpu_id = form.cpu_id.trim()
    if (hasHardwareKey('disk_serial')) payload.disk_serial = form.disk_serial.trim()
    if (hasHardwareKey('mac_addresses')) {
      payload.mac_addresses = form.mac_addresses
        .split(',')
        .map((item) => item.trim())
        .filter(Boolean)
    }
    return payload
  }

  async function submitIssue() {
    if (!selectedProjectId || !form.planId) return
    if (!form.subjectName.trim()) {
      toast.error('请输入授权对象')
      return
    }
    if (!form.notBefore || !form.notAfter) {
      toast.error('请选择有效期')
      return
    }

    setIssuing(true)
    try {
      await issueLicense(selectedProjectId, {
        subject: {
          name: form.subjectName.trim(),
          email: form.subjectEmail.trim(),
          organization: form.subjectOrg.trim(),
        },
        plan_id: form.planId,
        not_before: new Date(form.notBefore).toISOString(),
        not_after: new Date(form.notAfter).toISOString(),
        hardware: getHardwarePayload(),
      })
      toast.success('License 已签发')
      setDrawerOpen(false)
      await loadLicenses()
    } catch (error) {
      toast.error(getErrorMessage(error, '签发 License 失败'))
    } finally {
      setIssuing(false)
    }
  }

  async function handleDownload(record: LicenseRecord) {
    setDownloadingId(record.id)
    try {
      saveBlobFile(await downloadLicense(record.id))
    } catch (error) {
      toast.error(getErrorMessage(error, '下载 License 失败'))
    } finally {
      setDownloadingId(undefined)
    }
  }

  return (
    <>
      <Header>
        <div className='ms-auto flex items-center space-x-2'>
          <ThemeSwitch />
          <ConfigDrawer />
          <ProfileDropdown />
        </div>
      </Header>

      <Main>
        <div className='mb-4 flex flex-wrap items-center justify-between gap-3'>
          <div>
            <h1 className='text-2xl font-bold tracking-tight'>License 管理</h1>
            <p className='text-muted-foreground'>按项目签发、查看与下载 License</p>
          </div>
          <div className='flex items-center gap-2'>
            <Button variant='outline' size='sm' onClick={() => void loadLicenses()}>
              <RefreshCw className={loading ? 'animate-spin' : ''} />
              刷新
            </Button>
            <Button size='sm' onClick={openIssueDrawer}>
              <Plus />
              签发 License
            </Button>
          </div>
        </div>

        <Card className='mb-4'>
          <CardContent className='flex flex-wrap gap-3 pt-6'>
            <Select
              value={selectedProjectId ? String(selectedProjectId) : undefined}
              onValueChange={(value) => selectProject(Number(value))}
              disabled={loadingProjects || projects.length === 0}
            >
              <SelectTrigger className='w-[220px]'>
                <SelectValue placeholder='选择项目' />
              </SelectTrigger>
              <SelectContent>
                {projects.map((project) => (
                  <SelectItem key={project.id} value={String(project.id)}>
                    {project.name} · {project.key_bits} bit
                  </SelectItem>
                ))}
              </SelectContent>
            </Select>
            <div className='relative min-w-[220px] flex-1'>
              <Search className='absolute start-2.5 top-2.5 size-4 text-muted-foreground' />
              <Input
                className='ps-8'
                placeholder='搜索客户 / 邮箱 / UUID / 套餐'
                value={keyword}
                onChange={(e) => setKeyword(e.target.value)}
              />
            </div>
            <Select value={stateFilter} onValueChange={setStateFilter}>
              <SelectTrigger className='w-[140px]'>
                <SelectValue placeholder='有效性' />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value='all'>全部状态</SelectItem>
                <SelectItem value='active'>生效中</SelectItem>
                <SelectItem value='upcoming'>未开始</SelectItem>
                <SelectItem value='expired'>已过期</SelectItem>
              </SelectContent>
            </Select>
          </CardContent>
        </Card>

        <Card>
          <CardHeader>
            <CardTitle>License 列表</CardTitle>
            <CardDescription>
              {selectedProjectId
                ? `共 ${filtered.length} 条`
                : '请先选择项目'}
            </CardDescription>
          </CardHeader>
          <CardContent className='overflow-x-auto'>
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>授权对象</TableHead>
                  <TableHead>UUID</TableHead>
                  <TableHead>套餐</TableHead>
                  <TableHead>状态</TableHead>
                  <TableHead>有效期</TableHead>
                  <TableHead>功能</TableHead>
                  <TableHead>签发时间</TableHead>
                  <TableHead className='text-end'>操作</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                {!selectedProjectId ? (
                  <TableRow>
                    <TableCell colSpan={8} className='h-24 text-center text-muted-foreground'>
                      请先选择项目
                    </TableCell>
                  </TableRow>
                ) : loading ? (
                  <TableRow>
                    <TableCell colSpan={8} className='h-24 text-center'>
                      <Loader2 className='mx-auto animate-spin' />
                    </TableCell>
                  </TableRow>
                ) : filtered.length === 0 ? (
                  <TableRow>
                    <TableCell colSpan={8} className='h-24 text-center text-muted-foreground'>
                      暂无 License
                    </TableCell>
                  </TableRow>
                ) : (
                  filtered.map((record) => {
                    const state = getLicenseState(record)
                    return (
                      <TableRow key={record.id}>
                        <TableCell>
                          <div className='font-medium'>{record.subject_name}</div>
                          <div className='text-xs text-muted-foreground'>
                            {record.subject_email || '-'}
                          </div>
                        </TableCell>
                        <TableCell className='max-w-[180px] truncate font-mono text-xs'>
                          {record.uuid}
                        </TableCell>
                        <TableCell>{record.plan_name || record.plan || '-'}</TableCell>
                        <TableCell>
                          <Badge variant={stateVariant(state)}>{licenseStateText(state)}</Badge>
                        </TableCell>
                        <TableCell className='text-xs'>
                          {formatPeriod(record.not_before, record.not_after)}
                        </TableCell>
                        <TableCell>
                          <div className='flex max-w-[200px] flex-wrap gap-1'>
                            {record.features.length ? (
                              record.features.map((item) => (
                                <Badge key={item} variant='outline'>
                                  {item}
                                </Badge>
                              ))
                            ) : (
                              <span className='text-muted-foreground'>未配置</span>
                            )}
                          </div>
                        </TableCell>
                        <TableCell>{formatDateTime(record.created_at)}</TableCell>
                        <TableCell className='text-end'>
                          <div className='flex justify-end gap-1'>
                            <Button
                              size='sm'
                              variant='outline'
                              onClick={() => {
                                setDetailRecord(record)
                                setDetailOpen(true)
                              }}
                            >
                              详情
                            </Button>
                            <Button
                              size='sm'
                              variant='outline'
                              disabled={downloadingId === record.id}
                              onClick={() => void handleDownload(record)}
                            >
                              下载
                            </Button>
                          </div>
                        </TableCell>
                      </TableRow>
                    )
                  })
                )}
              </TableBody>
            </Table>
          </CardContent>
        </Card>
      </Main>

      <Sheet open={drawerOpen} onOpenChange={setDrawerOpen}>
        <SheetContent className='w-full overflow-y-auto sm:max-w-xl'>
          <SheetHeader>
            <SheetTitle>签发 License</SheetTitle>
          </SheetHeader>
          <div className='grid gap-4 px-4 py-2'>
            <div className='grid gap-2'>
              <Label>授权对象</Label>
              <Input
                value={form.subjectName}
                onChange={(e) => setForm((s) => ({ ...s, subjectName: e.target.value }))}
                placeholder='请输入客户或组织名称'
              />
            </div>
            <div className='grid gap-2'>
              <Label>邮箱</Label>
              <Input
                value={form.subjectEmail}
                onChange={(e) => setForm((s) => ({ ...s, subjectEmail: e.target.value }))}
                placeholder='请输入邮箱'
              />
            </div>
            <div className='grid gap-2'>
              <Label>组织</Label>
              <Input
                value={form.subjectOrg}
                onChange={(e) => setForm((s) => ({ ...s, subjectOrg: e.target.value }))}
                placeholder='请输入组织'
              />
            </div>
            <div className='grid gap-2'>
              <Label>套餐</Label>
              <Select
                value={form.planId ? String(form.planId) : undefined}
                onValueChange={(value) =>
                  setForm((s) => ({ ...s, planId: Number(value) }))
                }
              >
                <SelectTrigger>
                  <SelectValue placeholder='请选择套餐' />
                </SelectTrigger>
                <SelectContent>
                  {enabledPlans.map((item) => (
                    <SelectItem key={item.id} value={String(item.id)}>
                      {item.name} · {item.code}
                    </SelectItem>
                  ))}
                </SelectContent>
              </Select>
              {selectedPlan && (
                <p className='text-xs text-muted-foreground'>
                  功能 {selectedPlan.features.length} 个，用户{' '}
                  {selectedPlan.max_users || '不限'}，设备 {selectedPlan.max_devices || '-'}
                </p>
              )}
            </div>
            <div className='grid grid-cols-2 gap-3'>
              <div className='grid gap-2'>
                <Label>生效时间</Label>
                <Input
                  type='datetime-local'
                  value={form.notBefore}
                  onChange={(e) => setForm((s) => ({ ...s, notBefore: e.target.value }))}
                />
              </div>
              <div className='grid gap-2'>
                <Label>过期时间</Label>
                <Input
                  type='datetime-local'
                  value={form.notAfter}
                  onChange={(e) => setForm((s) => ({ ...s, notAfter: e.target.value }))}
                />
              </div>
            </div>
            <div className='grid gap-2'>
              <Label>硬件绑定</Label>
              <div className='flex flex-wrap gap-3'>
                {hardwareOptions.map((item) => (
                  <label key={item.value} className='flex items-center gap-2 text-sm'>
                    <Checkbox
                      checked={hasHardwareKey(item.value)}
                      onCheckedChange={(checked) =>
                        toggleHardwareKey(item.value, checked === true)
                      }
                    />
                    {item.label}
                  </label>
                ))}
              </div>
            </div>
            {hasHardwareKey('hostname') && (
              <div className='grid gap-2'>
                <Label>主机名</Label>
                <Input
                  value={form.hostname}
                  onChange={(e) => setForm((s) => ({ ...s, hostname: e.target.value }))}
                  placeholder='例如：office-mac'
                />
              </div>
            )}
            {hasHardwareKey('cpu_id') && (
              <div className='grid gap-2'>
                <Label>CPU ID</Label>
                <Input
                  value={form.cpu_id}
                  onChange={(e) => setForm((s) => ({ ...s, cpu_id: e.target.value }))}
                  placeholder='例如：BFEBFBFF000906EA'
                />
              </div>
            )}
            {hasHardwareKey('disk_serial') && (
              <div className='grid gap-2'>
                <Label>磁盘序列号</Label>
                <Input
                  value={form.disk_serial}
                  onChange={(e) => setForm((s) => ({ ...s, disk_serial: e.target.value }))}
                  placeholder='例如：DISK-SERIAL-001'
                />
              </div>
            )}
            {hasHardwareKey('mac_addresses') && (
              <div className='grid gap-2'>
                <Label>MAC 地址</Label>
                <Input
                  value={form.mac_addresses}
                  onChange={(e) =>
                    setForm((s) => ({ ...s, mac_addresses: e.target.value }))
                  }
                  placeholder='多个地址用英文逗号分隔'
                />
              </div>
            )}
          </div>
          <SheetFooter>
            <Button variant='outline' onClick={() => setDrawerOpen(false)}>
              取消
            </Button>
            <Button disabled={issuing} onClick={() => void submitIssue()}>
              {issuing && <Loader2 className='animate-spin' />}
              签发
            </Button>
          </SheetFooter>
        </SheetContent>
      </Sheet>

      <Sheet open={detailOpen} onOpenChange={setDetailOpen}>
        <SheetContent className='w-full overflow-y-auto sm:max-w-lg'>
          <SheetHeader>
            <SheetTitle>License 详情</SheetTitle>
          </SheetHeader>
          {detailRecord ? (
            <div className='space-y-3 px-4 py-2 text-sm'>
              <DetailItem label='UUID' value={detailRecord.uuid} mono />
              <DetailItem label='授权对象' value={detailRecord.subject_name} />
              <DetailItem label='邮箱' value={detailRecord.subject_email || '-'} />
              <DetailItem label='组织' value={detailRecord.subject_org || '-'} />
              <DetailItem
                label='套餐'
                value={detailRecord.plan_name || detailRecord.plan || '-'}
              />
              <DetailItem
                label='有效期'
                value={formatPeriod(detailRecord.not_before, detailRecord.not_after)}
              />
              <DetailItem
                label='额度'
                value={`用户 ${detailRecord.limits?.max_users || '不限'} / 设备 ${detailRecord.limits?.max_devices || '-'}`}
              />
              <div>
                <div className='mb-1 text-muted-foreground'>功能</div>
                <div className='flex flex-wrap gap-1'>
                  {detailRecord.features.length ? (
                    detailRecord.features.map((item) => (
                      <Badge key={item} variant='outline'>
                        {item}
                      </Badge>
                    ))
                  ) : (
                    <span className='text-muted-foreground'>未配置</span>
                  )}
                </div>
              </div>
            </div>
          ) : (
            <p className='px-4 text-sm text-muted-foreground'>暂无详情</p>
          )}
        </SheetContent>
      </Sheet>
    </>
  )
}

function DetailItem({
  label,
  value,
  mono,
}: {
  label: string
  value: string
  mono?: boolean
}) {
  return (
    <div>
      <div className='mb-1 text-muted-foreground'>{label}</div>
      <div className={mono ? 'break-all font-mono text-xs' : ''}>{value}</div>
    </div>
  )
}
